baseURL = "https://codewithcat.live/"
languageCode = "en-us"
title = "Let's code with cat"
theme="base16"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

[params]
  author = "Thinh Nguyen"
  github = "https://github.com/thinhnguyen1105"
  facebook = "https://facebook.com/thinhnguyen1105"
  og_image = "/image/thumbnail.jpg"
  ogimage = "/image/thumbnail.jpg"
  sitename = "Thinh Nguyen's Journey"